### ISSUE TITLE
compute_distances() fails

### ISSUE THREAD

**Issue by EricJi150** [jonasricker/aeroblade#1]
When running `python scripts/run_aeroblade.py` compute_distance always fails and gets killed. The error is:

> You are using a model of type xlm-roberta to instantiate a model of type M-CLIP. This is not supported for all configurations of models and can yield errors.
> Killed

**Comment by jonasricker** [comment]
The warning about xlm-roberta is expected and should not be an issue. The "Killed" sound like you might be running out of memory. Can you check your RAM usage while running the script?

**Comment by EricJi150** [comment]
looks like memory usage hits 100% and the program is killed, any suggestions? I am just trying to generate the LPIPS difference between an original and reconstructed image to get a similar difference image as shown in figure 1 of the paper.

**Comment by jonasricker** [comment]
How much memory do you have and how large is the image?

**Comment by EricJi150** [comment]
My system has a total of about 334 GB. I am trying to use an image of size 512x512.

**Comment by jonasricker** [comment]
Ok, then memory should definitely not be a problem. Could you try to debug where exactly the memory starts to fill up? 

Btw, you could also have a look at `experiments/00_other_figures.ipynb` to recreate Figure 1, since `run_aeroblade.py` does not directly yield the error maps.

**Comment by EricJi150** [comment]
`00_other_figures.ipynb` is what I was looking for thanks! However, I inputted an image with inpainted objects created from SD 1-2, but did not get the results I expected clearly outlining the mask.

![inpainted_dog](https://github.com/jonasricker/aeroblade/assets/73372943/87fa169d-7492-466a-8477-b134ec49d695)
![image](https://github.com/jonasricker/aeroblade/assets/73372943/e9a0e70b-f977-4a5f-add1-53da58e24d6b)

**Comment by jonasricker** [comment]
If you created the inpainting using SD1.2 you would have to compute the reconstruction using the AE from SD1. So in the notebook, replace `repo_id="stabilityai/stable-diffusion-2-base"` with `repo_id="CompVis/stable-diffusion-v1-1"` within the call(s) to `compute_reconstructions`.

**Comment by EricJi150** [comment]
I switched the AE, but doesn't seem like I can achieve the results from the paper. I have the mask for reference.

![download](https://github.com/jonasricker/aeroblade/assets/73372943/85bf92ff-af28-41d0-977e-9408819f9292)
![download (1)](https://github.com/jonasricker/aeroblade/assets/73372943/24187942-7957-47ce-9ee7-7923b2a94ff9)

**Comment by jonasricker** [comment]
From the last image it looks like the parts outside the mask are also passed through the autoencoder (one can tell by the malformed wooden grid in the back of the bench). In this case, our method cannot locate the inpainted regions, because the entire image has a low reconstruction error. In our experiments, the regions outside the mask were copied from the original image. I guess that different implementations of inpainting might handle this differently.

**Comment by EricJi150** [comment]
Makes sense thank you for your help!

**Comment by jonasricker** [comment]
Please have a look at #2 for more info on how to inpaint without modifying the unmasked area.
