### ISSUE TITLE
Reproduction of Figure 6

### ISSUE THREAD

**Issue by Oxydeas** [jonasricker/aeroblade#2]
Hello,

I am unable to reproduce the results of Figure 6 and was wondering if you could share some details on how you generated the figure ?

After reading #1 I made sure that parts outside the masked area were not passed through the autoencoder during the inpainting process, but I am not sure of what you mean by "the regions outside the mask were copied from the original image". At which step of the procedure does this happen ?

Currently, my pipeline looks something like this
```python
image = ... # 512x512x3
mask = ... # 512x512

pipe = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting")
inpainted_image = pipe(prompt, image, mask, padding_mask_crop=16, ...)

reconstruction_error_map = compute_dist(inpainted_image, VAE_Dec(VAE_Enc(inpainted_image)))
```
But the results are not convincing. While the reconstruction error is somewhat lower in the inpainted zone, it is far from the extremely convincing shadows of Figure 6.  

_Original image_
![Original image](https://github.com/jonasricker/aeroblade/assets/79522946/8767bbfe-7350-4162-bf65-2245c41d9b1c)
_Mask_
![Mask](https://github.com/jonasricker/aeroblade/assets/79522946/e46baf94-272a-45ae-9821-93f81e7a054d)
_Error map (LPIPS 2)_
![Error map](https://github.com/jonasricker/aeroblade/assets/79522946/e22ec6df-3f7b-443d-b5e6-5584213b9782)

**Comment by jonasricker** [comment]
> After reading https://github.com/jonasricker/aeroblade/issues/1 I made sure that parts outside the masked area were not passed through the autoencoder during the inpainting process, but I am not sure of what you mean by "the regions outside the mask were copied from the original image". At which step of the procedure does this happen ?

It means that the unmasked area is not affected by the model at all. In the [docs of diffusers](https://huggingface.co/docs/diffusers/using-diffusers/inpaint#non-inpaint-specific-checkpoints) they describe how to achieve this:

>If preserving the unmasked area is important for your task, you can use the VaeImageProcessor.apply_overlay method to force the unmasked area of an image to remain the same at the expense of some more unnatural transitions between the masked and unmasked areas.

I used their example code to generate two versions of the inpainted image: the first repaints the entire image, the second leaves the unmasked regions untouched.
![grafik](https://github.com/jonasricker/aeroblade/assets/64612045/a9d3ad91-d143-4ad6-9890-60f9c8294d0b)

Looking at the reconstruction errors, we see that AEROBLADE can only localize the inpainted region in the second case.
![grafik](https://github.com/jonasricker/aeroblade/assets/64612045/9283c071-f2fa-4edf-883a-228e54d95559)

I included the code to generate these figures in [experiments/00_other_figures.ipynb](https://github.com/jonasricker/aeroblade/blob/main/experiments/00_other_figures.ipynb).

**Comment by Oxydeas** [comment]
Thanks a lot for your help!
