### ISSUE TITLE
Pretrained models unavailable

### ISSUE THREAD

**Issue by RizhaoCai** [jonasricker/aeroblade#5]
![image](https://github.com/jonasricker/aeroblade/assets/37952703/09aa544b-ca56-4b5c-bae6-7f61623c8d1c)

**Comment by breadxiexie** [comment]
Do I need a pretrained model to detect this? Can you tell me where this link is?

**Comment by jonasricker** [comment]
@breadxiexie there is no dedicated pretrained model, since our method is training-free. It only uses different autoencoders of diffusion models and the LPIPS similarity metric, which are downloaded on-the-fly when running the code.
