### ISSUE TITLE
Kandinsky weight loading issue.

### ISSUE THREAD

**Issue by WaiBiBaBolmc** [jonasricker/aeroblade#7]
Your work is inspirational! However, during the replication process, I downloaded the pretrained weights of Kandinsky to my local machine and encountered the following warning during loading:
"You are using a model of type xlm-roberta to instantiate a model of type M-CLIP. This is not supported for all configurations of models and can yield errors."
Despite such output, the code still ran completely. Could you tell me if this prompt might negatively impact the metrics? And how should I resolve it?

**Comment by jonasricker** [comment]
Thank you for your interest in our work. We encountered this warning as well, but we followed the official code and the images look fine, so it should not have an effect on the results.
