### ISSUE TITLE
how to judge whether a picture is AI generated just by reconstruction error

### ISSUE THREAD

**Issue by Fu61** [jonasricker/aeroblade#8]
hey, I read your paper, nice method, just seems I can only get the reconstruction error between the origin image and reconstructed image, then how can I know whether it's AI generated by the reconstruction error? Is there any threshold setting? Actually the key problem is which you said in the section 5.4 in your paper(Relation Between Image Complexity and Reconstruction Error), the simple real image also trend to have small reconstruction error, so maybe the anwser need to also consider the complexity of the image? Hope to get your response, thanks.

**Comment by Vanleya** [comment]
have u solved yet?
